### ISSUE TITLE
Crates.io release

### ISSUE THREAD

**Issue by clehner** [spruceid/didkit#119]
Publish `didkit` `v0.2.0` to `crates.io`.

- [x] Publish `ssi v0.2.0` (and workspace crates) to `crates.io`: https://github.com/spruceid/ssi/issues/136
  - [ ] Depend on `ssi` using registry versions alongside path dependency: done except for `didkit-node` and `didkit-web`
- [x] Change author names to Spruce Systems, Inc.: https://github.com/spruceid/didkit/pull/122
- [x] Update changelog with changes since `v0.1.0`: #123 
- [x] `didkit` ready to publish (`cargo publish --dry-run` succeeds): https://github.com/spruceid/didkit/pull/139
  - [x] `didkit` published to `crates.io`: #144
    - [ ] Depend on `didkit` using registry version alongside path dependency: done except for `didkit-node` and `didkit-web`
- [ ] Remove git dependency (`neon-serde` fork) in `didkit-node`, or skip publishing `didkit-node` (maybe more important this one is published with `npm` than to `crates.io`?): skipping; `didkit-node` and/or `didkit-wasm` can go to a npm registry instead.
- [x] Workspace crates ready to publish - CLI, HTTP, ~~Node(?), WASM(?)~~: Add [package metadata](https://doc.rust-lang.org/cargo/reference/manifest.html#the-package-section) as needed.
  - [x] Workspace crates published to `crates.io`
    - [x] didkit-http: https://github.com/spruceid/didkit/pull/147#issuecomment-819610819
    - [x] didkit-cli: https://github.com/spruceid/didkit/pull/146#issuecomment-819540348

**Comment by clehner** [comment]
Crates `didkit`, `didkit-cli` and `didkit-http` have been released.

Remaining/next issues: #141, #148
